name: Build and deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Client
        #id: build-client
        run: |
          cd client
          npm i
          npm run test
          npm run build

      - name: Build Server
        #id: build-server
        run: |
          cd server
          npm i
          npm run test
      
      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.MY_EMAIL}}
          appdir: "server"
        env:
          NODE_ENV: production
          PORT: 8083
          MONGO_URL: ${{ secrets.MONGO_URL }}